# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Worfklow triggerer name'
        # Default value if no value is explicitly provided
        default: 'Anonymous'
        # Input has to be provided for the workflow to run
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  buildREADME:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: Checkout current repo to main branch 
      uses: actions/checkout@v1 
    - name: Setup Nodejs 
      uses: actions/setup-node@v1
      with: 
        node-version: '13.x'
    - name: Cache deps and build outputs to improve workflow exec time
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies 
      run: npm install 
    - name: Run ReadMe generation script 
      run: node index.js 
    - name: Commit and push new README to repo 
      uses: mikeal/publish-to-github-action@master
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
